require 'chefspec'
require_relative 'spec_helper'

describe 'strainer-berkshelf-chefspec-recursive-bug::encrypted_data_bag_spec' do
  let(:chef_run) {
    chef_run = create_chefspec_runner
    chef_run.converge described_recipe
  }

  let(:demo_user_data_bag) {
      {"id"=>"demo",
         "groups"=>["demo"],
         "uid"=>1020,
         "gid"=>1020,
         "shell"=>"/bin/bash",
         "comment"=>"Demo Account",
         "password"=>"!!",
         "ssh_keys"=>
           ["ssh-rsa TODO: Demo key\n"]
       }
    }

  it 'should set up the environment with some secure AWS keys' do
    pending 'Do some more stuff'
    file_content = <<-EOENV.strip_heredoc
      # This file generated by chef (strainer-berkshelf-chefspec-recursive-bug::encrypted_data_bag), do not edit
      AWS_DB_BACKUP_KEY_ID='DATABASEBACKUPID'
      AWS_DB_BACKUP_SECRET_KEY='DatabaseBackup+SecretAccessKey++test'
      AWS_MEDIA_ASSETS_KEY_ID='MEDIAASSETSKEYID'
      AWS_MEDIA_ASSETS_SECRET_KEY='MediaAssets+SecretAccessKey+++++test'
      AWS_S3_LOG_UPLOAD_KEY_ID='S3LOGUPLOAD00KEY00ID'
      AWS_S3_LOG_UPLOAD_SECRET_KEY='S3LogUpload+SecretAccessKey+++++++++test'
      AWS_GITHUB_REPO_BACKUP_KEY_ID='GITHUBREPOBACKUP00ID'
      AWS_GITHUB_REPO_BACKUP_SECRET_KEY='GithubRepoBackup+SecretAccessKey++++test'
    EOENV
    expect(chef_run).to create_file_with_content '/etc/environment', file_content
  end

end
